# This is a basic workflow to help you get started with Actions

name: Secret-token-leaks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read
jobs:
  TruffleHog:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@bc27fef7bc006152f3fa872c4679f0038d55e925
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          args: --debug
          
